### ISSUE TITLE
Cannot resolve method 'addOnPageChangeListener()'

### ISSUE THREAD

**Issue by CWlf** [Chabbal/slidingdotsplash#1]
Hi,
I have the object error when I try to add the listener:

`		SlidingSplashView splashView  = (SlidingSplashView) findViewById(R.id.splash);
		splashView.addOnPageChangeListener(this);`

I don't understand why give me this error; I had implemented OnPageChangeListener.

Can you help me?
Thank you

**Comment by TimidLupus** [comment]
You have to implement following listener in your activity or fragment.

`implements ViewPager.OnPageChangeListener`

**Comment by CWlf** [comment]
I have implemented ViewPager.OnPageChangeListener in my Fragment:

```
public class MyActivity extends FragmentActivity implements ViewPager.OnPageChangeListener {
}
```
I have also related methods:

```
        @Override
	public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {

	}

	@Override
	public void onPageSelected(int position) {

	}

	@Override
	public void onPageScrollStateChanged(int state) {

	}
```

I still have the same error; may depend on Support-v4 library?
`'com.android.support:support-v4:25.1.0'`

Thank you

**Comment by TimidLupus** [comment]
add the library to your gradle
